version: '3'
services:
  postgres:
    image: postgres:latest
    ports:
      - '5432:5432'
    env_file:
      - .env
    restart: always
    volumes: 
      - ./00-postgres.sql:/docker-entrypoint-initdb.d/postgres.sql
      - ./postgres-data:/var/lib/postgresql/data

  mysql:
    image: mysql:latest
    ports:
      - '3306:3306'
    env_file:
      - .env
    restart: always
    volumes:
      - ./mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - '8089:80'
    depends_on:
      - mysql

  hasura:
    image: hasura/graphql-engine:latest
    ports:
      - '8084:8080'
    depends_on:
      - 'postgres'
    env_file:
      - .env
    restart: always

  server:
    image: server
    build: 
      context: .
      dockerfile: src/Dockerfile
    ports:
      - 5078:5078
    depends_on: 
      - postgres
